### ISSUE TITLE
[IAM] Add all project capability to flexibleengine_identity_role_assignment_v3

### ISSUE THREAD

**Issue by thivr** [FlexibleEngineCloud/terraform-provider-flexibleengine#1110]
Hello

May you add the all projects capability to these resource flexibleengine_identity_role_assignment_v3 ?

This is the corresponding API call https://docs.prod-cloud-ocb.orange-business.com/api/iam/iam_02_0519.html

Thanks^^

**Comment by ShiChangkuo** [comment]
@thivr the resource `flexibleengine_identity_role_assignment_v3` will be replaced by `flexibleengine_identity_group_role_assignment ` in v1.46.0.

If you want to assign a role with all projects, please open a service ticket to obtain the access of [Granting Permissions to a User Group for All Projects](https://docs.prod-cloud-ocb.orange-business.com/api/iam/iam_02_0519.html).
Otherwise, we will get the following error:

{
  "error": {
    "code": 401,
    "message": "The request you have made requires authentication.",
    "title": "Unauthorized"
  }
}
