### ISSUE TITLE
[Feature Request] Obtain Client IP Address on ELB Listener

### ISSUE THREAD

**Issue by vlandemaine-orange** [FlexibleEngineCloud/terraform-provider-flexibleengine#609]
Hello, 

We have actually a need about the configuration of the **X-Forwarded-For** on an ELB Listener in order to retrieve the real IP address of the client on backend server.

Actually, we don't have any parameter in the Terraform resource **flexibleengine_elb_listener** to configure "**Obtain Client IP Address**" but this parameter is present on the Flexible Engine console when we create a ELB listener.

It is possible to add this parameter on the flexibleengine_elb_listener Terraform resource ?

Regards,

Valentin LANDEMAINE (OCB/PS)

**Comment by ShiChangkuo** [comment]
@vlandemaine-orange we should update API version to [v3](https://docs.prod-cloud-ocb.orange-business.com/api/elb/elb_zq_jt-v3_0001.html) to support this parameter.

can you install the TOA plug-in to obtain real IP addresses as a workaround? For details, see [How Can I Obtain the IP Address of a Client?](https://docs.prod-cloud-ocb.orange-business.com/usermanual/elb/elb_faq_0090.html)

**Comment by Pseudodevincent** [comment]
Hello @vlandemaine-orange @ShiChangkuo , TOA plug-in is not necessary anymore. Source IP transfer on L4 listeners can be enabled through the console and through API. When enabled, backend servers get client source IP instead of ELB source IP.
On L7 listeners the X-Forwared-For is enabled by default.
Anyway, the ELB Listener API which allows source IP on L4 listeners is V3.
Terraform provider should use this new API version.

**Comment by ShiChangkuo** [comment]
I wil try to call the v3 API in the provider, and keep the resource name to `flexibleengine_lb_listener_v2`

**Comment by Karreg** [comment]
Hello,

The same is needed here! Thanks!

**Comment by vlandemaine-orange** [comment]
Hi @ShiChangkuo,

It's possible to create a minor release to apply this changes in the provider ?

Thanks
